name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dev dependencies
        run: pip install -e '.[dev]'
      - name: Run unit & integration tests
        run: pytest -q
      - name: CLI help flags
        run: |
          python -m signature_recovery.cli.main --help | grep --quiet "threads" || echo "threads flag not found"
          recover-signatures --help | grep -E "(extract|query|export)"
      - name: Verify CLI entry point
        run: |
          recover-signatures --help | grep -E "extract|query|export|metrics"
